### ISSUE TITLE
Non-local trailing whitespace sensitivity. 

### ISSUE THREAD

**Issue by Carreau** [stsewd/tree-sitter-rst#21]
Take the following that have no trailing whitespace.
```rst
::

    [[1., 0., 0.],
     [0., 1., 2.]]

::

    >>> np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported

You could also implement the reduce as follows::

    >>> def ufunc_reduce(ufct, *vectors):

.. seealso::
   :doc:`numpy-for-matlab-users`
```

It parses to 

```
document [0, 0] - [15, 0]
  literal_block [2, 4] - [3, 18]
  literal_block [7, 4] - [7, 83]
  paragraph [9, 0] - [11, 41]
    literal_block [11, 4] - [11, 41]
  directive [13, 0] - [13, 12]
    name: type [13, 3] - [13, 10]
  paragraph [14, 3] - [14, 32].  # this is wrong
    interpreted_text [14, 3] - [14, 32]
      role [14, 3] - [14, 8]
```

at 1 trailing whitespace after the first literal block:

```rst
::

    [[1., 0., 0.],
     [0., 1., 2.]]
 <- there is a whitespace here now
::

    >>> np.set_printoptions(threshold=sys.maxsize)  # sys module should be imported

You could also implement the reduce as follows::

    >>> def ufunc_reduce(ufct, *vectors):

.. seealso::
   :doc:`numpy-for-matlab-users`
```

And it parses properly.

```
document [0, 0] - [15, 0]
  literal_block [2, 4] - [3, 18]
  literal_block [7, 4] - [7, 83]
  paragraph [9, 0] - [11, 41]
    literal_block [11, 4] - [11, 41]
  directive [13, 0] - [14, 32]
    name: type [13, 3] - [13, 10]
    body: body [13, 12] - [14, 32]
      content [14, 3] - [14, 32]
```

Note: taken from there https://numpy.org/doc/stable/user/quickstart.html

https://user-images.githubusercontent.com/335567/144559626-0b1aeb7f-968d-4be3-99f3-9859f6e35abd.mov

**Comment by Carreau** [comment]
note that
```diff
 .. seealso::
-   :doc:`numpy-for-matlab-users`
+    :doc:`numpy-for-matlab-users`
```
Fixes it as well, and so does adding trailing space on other blanks lines like the line just above see-also

I'm not sure this is intended, and a "it should be consistently indented 3/4 spaces" is a valid answer,

**Comment by stsewd** [comment]
Thanks for reporting! I think this is a bug with the stack that keeps track of indentation levels

https://github.com/stsewd/tree-sitter-rst/blob/a5514617ae3644effa80d4696be428e4a371c01a/src/tree_sitter_rst/parser.c#L903-L907

probably it shouldn't be +1, but the actual indentation level of the block, or maybe there is a dedent missing.

I'm on vacations now, so I'll put some time to look at the bugs in the next days :D

**Comment by Carreau** [comment]
No worries, at some point I should also delve into tree sitter and
understand how it works, so that I can submit patches here directly when I
encounter issues.
