### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by zegervdv** [stsewd/tree-sitter-rst#38]
To be able to complete my integration into [cbfmt ](https://github.com/lukas-reineke/cbfmt/pull/6) it would make it easier if tree-sitter-rst was also available on crates.io. Apparently if you want to distribute a package there, all dependencies also need to be hosted on it. 

Would you consider adding it? I have no experience with it myself,  but I’m willing to help where I can. 

Thanks!

**Comment by stsewd** [comment]
Hi, I haven't published a package before either, but this looks like a great opportunity to do so, I'll try to do it this weekend

**Comment by zegervdv** [comment]
Great! Thanks a lot.

**Comment by stsewd** [comment]
Released! https://crates.io/crates/tree-sitter-rst

**Comment by zegervdv** [comment]
Thanks!
