### ISSUE TITLE
adding this repo to https://github.com/grantjenks/py-tree-sitter-languages

### ISSUE THREAD

**Issue by Carreau** [stsewd/tree-sitter-rst#39]
it looks like https://github.com/grantjenks/py-tree-sitter-languages is tryign to compile all tree-sitter languages in a single place. 

Would you be ok for me to send a PR there to add this repo as one of the language being built ?

**Comment by stsewd** [comment]
> Would you be ok for me to send a PR there to add this repo as one of the language being built ?

Sure, go ahead!

**Comment by stsewd** [comment]
Looks like the parser is already included
