### ISSUE TITLE
Tree sitter rst seem to miss linked text just after an opening `[`

### ISSUE THREAD

**Issue by Carreau** [stsewd/tree-sitter-rst#49]
Example from numpy linspace:

```
Return evenly spaced numbers over a specified interval.

Returns num evenly spaced samples, calculated over the
interval [`start`, `stop`].
```

The `` `start` `` will be part of the paragraph text and not an `interpreted_text` node.

This is not the case if the preceding charater is a `(`. I haven't exaustively tested sphinx, but it does work for `[`.

**Comment by Carreau** [comment]
Many thanks for the rapid update, and happy new year 2024 I guess.

**Comment by stsewd** [comment]
Happy new year! :tada:
